module Academico::Aluno::Infra::TelefoneRepositories::ActiveRecord
end
class ApplicationRecord < ActiveRecord::Base
end
module Academico::Aluno::Infra::Repositories::ActiveRecord
end
class Academico::Aluno::Infra::TelefoneRepositories::ActiveRecord::Record::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
module Academico
end
module Academico::Infra
end
module Academico::Aluno::Infra
end
module Academico::Aluno::Infra::TelefoneRepositories
end
module Academico::Aluno::Infra::Repositories
end
class ActiveRecord::Associations::CollectionProxy < ActiveRecord::Relation
end
class ActiveRecord::Relation < Object
end
module ActiveRecord::Associations
end
