module Academico
  module Aluno
    class Matricular
      class SuccessMailer < Academico::ApplicationMailer
        def self.send_mail: (Academico::Aluno::Entity aluno) -> void
      end
    end
  end
end
