---
name: actionview
version: '6.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 0aad7a9acb950f56c6e836499373555f1071eb3d
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
