# TypeProf 0.21.7

# Classes
module Academico
  module Infra
    module Aluno
      module Repositories
        module ActiveRecord
          class Impl
            include Academico::Domain::Aluno::_Repository
          end
        end
      end
    end
  end
end
