module Marketing
  module Lead
    class Convert
      def initialize: (email: String) -> void

      def self.call: (email: String) -> void

      def call: () -> void

      private

      attr_accessor email: String
    end
  end
end
