module Academico::Infra::Aluno::TelefoneRepositories::ActiveRecord
end
class ApplicationRecord < ActiveRecord::Base
end
module Academico::Infra::Aluno::Repositories::ActiveRecord
end
class Academico::Infra::Aluno::TelefoneRepositories::ActiveRecord::Record::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
module Academico
end
module Academico::Infra
end
module Academico::Infra::Aluno
end
module Academico::Infra::Aluno::TelefoneRepositories
end
module Academico::Infra::Aluno::Repositories
end
class ActiveRecord::Associations::CollectionProxy < ActiveRecord::Relation
end
class ActiveRecord::Relation < Object
end
module ActiveRecord::Associations
end
