module Marketing::Lead
end
class Marketing::ApplicationRecord < ActiveRecord::Base
end
module Finance::Client
end
class Finance::ApplicationRecord < ActiveRecord::Base
end
class Finance::Card::Entity::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
module Finance::Card
end
module Academico::Infra::Aluno::TelefoneRepositories::ActiveRecord
end
class Academico::ApplicationRecord < ActiveRecord::Base
end
module Academico::Infra::Aluno::Repositories::ActiveRecord
end
class Academico::Infra::Aluno::TelefoneRepositories::ActiveRecord::Record::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
module Academico::Domain::Curso
end
module Marketing
end
module Finance
end
class ActiveRecord::Associations::CollectionProxy < ActiveRecord::Relation
end
module Academico
end
module Academico::Infra
end
module Academico::Infra::Aluno
end
module Academico::Infra::Aluno::TelefoneRepositories
end
module Academico::Infra::Aluno::Repositories
end
module Academico::Domain
end
class ActiveRecord::Relation < Object
end
module ActiveRecord::Associations
end
