# TypeProf 0.21.7

# Classes
module Academico
  module Aluno
    interface _Repository
      def adicionar: (aluno: Entity) -> void
      def buscar_por_cpf: (Shared::Domain::Cpf) -> Entity
      def buscar_por_email: (String) -> Entity
      def buscar_todos: -> Array[Entity]
    end
  end
end
