# TypeProf 0.21.7

# Classes
module Academico
  module Domain
    module Aluno
      class Entity
        attr_accessor cpf: Shared::Domain::Cpf
        attr_accessor email: Email
        attr_accessor nome: String
        attr_accessor telefones: Array[Telefone]
        attr_accessor senha: String
        def initialize: (cpf: String, nome: String, email: String, senha: String) -> void
        def adicionar_telefone: (ddd: String, numero: String) -> void
        def one: -> Integer
      end
    end
  end
end
