class FormBuilder[F]
  def initialize: (untyped) -> void
  def input: (F) -> String
end

module FormHelpers
  type model_attributes = :full_name | :email
  def self.form_for: (untyped) { (FormBuilder[model_attributes]) -> void } -> void
end

module FormOuter
  def self.form_for: (untyped) { (FormBuilder[String]) -> void } -> void
end
