module Shared::Domain
  module Evento
    class Ouvinte
      def processa: (evento: _Evento) -> void

      def sabe_processar?: (evento: _Evento) -> bool

      def reage_ao?: (evento: _Evento) -> bool
    end
  end
end
