module Academico::App::Aluno
  class MatriculadoOuvinte < ::Shared::Domain::Evento::Ouvinte
    attr_accessor evento: Finance::Client::Enrolled

    def reage_ao: (evento: Finance::Client::Enrolled) -> void

    def matricular_aluno: () -> void
  end
end
