# TypeProf 0.21.7

# Classes
module Academico
  module Infra
    module Aluno
      module Repositories
        module ActiveRecord
          class Impl < ::Academico::Domain::Aluno::Repository
            def adicionar: (aluno: Domain::Aluno::Entity) -> void
          end
        end
      end
    end
  end
end
