---
name: addressable
version: '2.8'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 4f55d83688a772342f0d96966cd51d06af03c2c8
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
