module Shared::Domain
  module Evento
    class Ouvinte
      def processa: (evento: _Evento) -> void

      def sabe_processar?: (evento: Class) -> bool

      def reage_ao: (evento: _Evento) -> void
    end
  end
end
