module Shared
  module Domain
    module Evento
      class Publicador
        def adicionar_ouvinte: (ouvinte: Ouvinte) -> void

        def publicar: (evento: _Evento) -> void

        private

        def ouvintes: () -> Array[Ouvinte]
      end
    end
  end
end
