---
name: observer
version: '0.1'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: eb6867fdb70e82e3aac6b51623ed1b6760c3c072
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
