module Academico::Aluno
  class Matricular
    def initialize: (?aluno_repository: Academico::Aluno::_Repository, aluno_dto: Dto) -> void

    def call: () -> bool

    attr_accessor errors: ActiveModel::Errors

    private

    attr_accessor aluno_repository: Academico::Aluno::_Repository
    attr_accessor aluno_dto: Dto

    def publicar_evento: (aluno: Academico::Aluno::Entity) -> void
  end
end
