module Academico
  module Aluno
    class Matricular
      def initialize: (aluno_repository: Academico::Aluno::_Repository,
                        publicador_de_evento: Shared::Evento::Publicador) -> void

      def call: (aluno_dto: Dto) -> void

      private

      attr_accessor aluno_repository: Academico::Aluno::_Repository

      attr_accessor publicador_de_evento: Shared::Evento::Publicador
    end
  end
end
